FROM centos:7

COPY conf/nginx.repo /etc/yum.repos.d/nginx.repo

# Install PHP 7.3 on Centos7: https://linuxize.com/post/install-php-7-on-centos-7/
RUN \
    yum install -y nginx epel-release yum-utils && \
    yum install -y http://rpms.remirepo.net/enterprise/remi-release-7.rpm && \
    yum-config-manager --enable remi-php73 && \
    yum -y install php php-common php-fpm php-cli && \
    yum clean all

RUN mkdir /nginx_php

COPY conf/nginx.conf /etc/nginx/conf.d/default.conf

COPY fruit /nginx_php

COPY test.php /nginx_php

COPY conf/start.sh /start.sh

RUN chmod +x /start.sh

CMD /start.sh