# First stage
FROM maven:3.6-alpine as builder

COPY app-maven /app

WORKDIR /app

RUN mvn package

# Second stage
# Final image will only contain this, removing all dependencies you do not need
FROM openjdk:8-alpine

COPY --from=builder /app/target/my-app-1.0-SNAPSHOT.jar /app.jar

CMD java -jar /app.jar